<?php

namespace AppBundle\Repository;

/**
 * UserGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
